/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AssinaturaExpiradaRouteImport } from './routes/assinatura-expirada'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppReceitasRouteImport } from './routes/_app/receitas'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppMercadosRouteImport } from './routes/_app/mercados'
import { Route as AppManualRouteImport } from './routes/_app/manual'
import { Route as AppListaRouteImport } from './routes/_app/lista'
import { Route as AppImportarRouteImport } from './routes/_app/importar'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppAssinaturaRouteImport } from './routes/_app/assinatura'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaExpiradaRoute = AssinaturaExpiradaRouteImport.update({
  id: '/assinatura-expirada',
  path: '/assinatura-expirada',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppMercadosRoute = AppMercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppListaRoute = AppListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura-expirada': typeof AssinaturaExpiradaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/assinatura': typeof AppAssinaturaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/importar': typeof AppImportarRoute
  '/lista': typeof AppListaRoute
  '/manual': typeof AppManualRoute
  '/mercados': typeof AppMercadosRoute
  '/produtos': typeof AppProdutosRoute
  '/receitas': typeof AppReceitasRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura-expirada': typeof AssinaturaExpiradaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/assinatura': typeof AppAssinaturaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/importar': typeof AppImportarRoute
  '/lista': typeof AppListaRoute
  '/manual': typeof AppManualRoute
  '/mercados': typeof AppMercadosRoute
  '/produtos': typeof AppProdutosRoute
  '/receitas': typeof AppReceitasRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/assinatura-expirada': typeof AssinaturaExpiradaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/_app/assinatura': typeof AppAssinaturaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/importar': typeof AppImportarRoute
  '/_app/lista': typeof AppListaRoute
  '/_app/manual': typeof AppManualRoute
  '/_app/mercados': typeof AppMercadosRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/receitas': typeof AppReceitasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura-expirada'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/registro'
    | '/assinatura'
    | '/categorias'
    | '/dashboard'
    | '/importar'
    | '/lista'
    | '/manual'
    | '/mercados'
    | '/produtos'
    | '/receitas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura-expirada'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/registro'
    | '/assinatura'
    | '/categorias'
    | '/dashboard'
    | '/importar'
    | '/lista'
    | '/manual'
    | '/mercados'
    | '/produtos'
    | '/receitas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/assinatura-expirada'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/registro'
    | '/_app/assinatura'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/importar'
    | '/_app/lista'
    | '/_app/manual'
    | '/_app/mercados'
    | '/_app/produtos'
    | '/_app/receitas'
    | '/_app/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AssinaturaExpiradaRoute: typeof AssinaturaExpiradaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-expirada': {
      id: '/assinatura-expirada'
      path: '/assinatura-expirada'
      fullPath: '/assinatura-expirada'
      preLoaderRoute: typeof AssinaturaExpiradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas': {
      id: '/_app/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mercados': {
      id: '/_app/mercados'
      path: '/mercados'
      fullPath: '/mercados'
      preLoaderRoute: typeof AppMercadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual': {
      id: '/_app/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lista': {
      id: '/_app/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof AppListaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar': {
      id: '/_app/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assinatura': {
      id: '/_app/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportarRoute: typeof AppImportarRoute
  AppListaRoute: typeof AppListaRoute
  AppManualRoute: typeof AppManualRoute
  AppMercadosRoute: typeof AppMercadosRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportarRoute: AppImportarRoute,
  AppListaRoute: AppListaRoute,
  AppManualRoute: AppManualRoute,
  AppMercadosRoute: AppMercadosRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AssinaturaExpiradaRoute: AssinaturaExpiradaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
